title: CS Conference Deadlines 
# email: 
description: Countdowns to top CS conference deadlines
author: Yanlin Wang

# url: "https://yanlinwang.github.io/DDL"
# domain: "https://yanlinwang.github.io/DDL"
# baseurl: "/DDL"
domain: ""
baseurl:""

# twitter_username:
# twitter_hashtag: 
# github_username: 
# github_repo: 

markdown: kramdown
# ga_id:

include: ['_pages']
